environment:
  name: us-west-2-prod-01
  profile: prod

image:
  repo: 820814109514.dkr.ecr.us-west-2.amazonaws.com/nanobot
  tag: stable

host: nanobot.visla.us

region: us-west-2
replica: 1

resources:
  requests:
    cpu: "1"
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

vislaAdminUsers:
  - porter.liu@visla.us
  - allan.song@visla.us
customModel:
  providerName: visla
  baseUrl: https://litellm.visla.us/v1
defaultModel: visla/gpt-5.6-luna

# aws web firewall
aws_partition: aws
aws_account_id: "820814109514"
waf_acl_id: 9baf75b0-f735-4384-b8cc-3531cf33c553
